global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gymtime-api'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['gymtime-api:80']
        labels:
          environment: 'development'
          service: 'gymtime-api'
