version: '3.9'

services:
  gymtime-db:
    image: postgres:16
    container_name: gymtime-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymtime
    ports:
      - "5432:5432"
    volumes:
      - gymtime_data:/var/lib/postgresql/data
    networks:
      - gymtime-network

volumes:
  gymtime_data:

networks:
  gymtime-network:
    driver: bridge